import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import { toast, ToastContainer } from 'react-toastify'
import styles from '../styles/Home.module.css'

export default function Home() {
    useEffect(() => {
        let isLogin = localStorage.getItem("login");
        console.log(isLogin);
        if(isLogin == "true"){
            toast.success('You successfuly logged in!', {
                position: toast.POSITION.TOP_RIGHT
                });
                localStorage.setItem("login", "false");
        }});
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <div className="h-52 text">
      Neki tekst
      </div>
    </main>
    <ToastContainer theme="dark" />
  </div>
  )
}
