/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { toast, ToastContainer } from 'react-toastify'
import styles from '../styles/Home.module.css'
import Doctors from '../public/Doctors.png'


export default function Home() {
  const router = useRouter();
    useEffect(() => {
      
        let isLogin = localStorage.getItem("login");
        let isActivationFalied = localStorage.getItem("activationFalied");
        if(isLogin == "true"){
            toast.success('You successfuly logged in!', {
                position: toast.POSITION.TOP_RIGHT
            });
        }
        if(isActivationFalied == "true"){
            toast.error('Accout activation failed! Check email again or contact support!', {
                position: toast.POSITION.TOP_RIGHT
            });
        }
        if(localStorage.getItem('wasLogged')==='false'){
          router.push('/stranica/SystemAdminLanding')
        }
        localStorage.removeItem('login');
        localStorage.removeItem('activationFalied');
    });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
        <div className="relative mb-16 h-1/2 rounded-b-[50%] overflow-hidden bg-emerald-800 text">
            <h1 className="absolute mb-64 text-6xl font-bold text-emerald-900 bg-emerald-300 backdrop-blur-md shadow-[0_0px_64px_43px_rgba(110,231,183,0.5)] py-4 px-8 bg-opacity-50 rounded-[64px] left-1/2 -translate-x-1/2 bottom-0"> We are here for you!</h1>
            <img src={Doctors.src} alt="Doctors" className=' my-auto'/>
        </div>
    </main>
    <ToastContainer theme="dark" />
  </div>
  )
}
